In [1]:
#Mulivariate linear regression
#SOURCE: Youtube: https://github.com/codebasics/py/blob/master/ML/2_linear_reg_multivariate/2_linear_regression_multivariate.ipynb

#Import needed libraries

import pandas as pd
import numpy as np
from sklearn import linear_model

In [14]:
#This is the full 2665 data set
df = pd.read_csv('boko_kill3.csv')
df

imonth  iday  nwound  nkill
0          7    27     0.0      0
1          7    27     0.0     77
2          7    27     0.0      0
3          7    27     0.0      0
4          7    27     0.0      0
...      ...   ...     ...    ...
2650      12    27     0.0      0
2651      12    28     0.0      0
2652      12    28     0.0      0
2653      12    28     0.0      0
2654      12    30     0.0      0

[2655 rows x 4 columns]

In [15]:
df.nwound.mean()

3.8790960451977403

In [16]:
df.nkill = df.nkill.fillna(df.nkill.median())
df

imonth  iday  nwound  nkill
0          7    27     0.0      0
1          7    27     0.0     77
2          7    27     0.0      0
3          7    27     0.0      0
4          7    27     0.0      0
...      ...   ...     ...    ...
2650      12    27     0.0      0
2651      12    28     0.0      0
2652      12    28     0.0      0
2653      12    28     0.0      0
2654      12    30     0.0      0

[2655 rows x 4 columns]

In [17]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('nkill',axis='columns'),df.nkill)

#dropped nkill and only kept the three variables of interest: day, month, and wounded


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
#Coefficients for three main variables

reg.coef_


array([-0.141116  , -0.0903381 ,  0.34868257])

In [19]:
#the intercept
reg.intercept_


9.155941345925843

In [20]:
#MEDICAL TEAM'S TYPICAL WOUNDING FACTOR
#If I had to provide aid on Oct(10) 24, and 4 people are injured I can expect 7 to die--NOT GOOD

reg.predict([[10, 24, 4]])



array([6.97139722])

In [21]:
#FOOD TEAM's TYPICAL WOUNDING FACTOR
reg.predict([[7, 27, 6]])

array([7.82109605])

In [22]:
#DS TEAM's TYPICAL WOUNDING FACTOR
#NOTE--THE IMPACT IS EVERYONE DIES--SEE VISUALIZATION AND STUDY RESULTS
reg.predict([[1, 27, 1]])

array([6.92437922])